### ISSUE TITLE
Remove Keys

### ISSUE THREAD

**Issue by coolrazor007** [git-ogawa/ansible-collection-yaml#2]
Whereas this works well, it would be very nice to be able to remove keys from YAML entirely.

**Comment by git-ogawa** [comment]
Hi coolrazor007.

If you want to remove all keys in a YAML file, is it not enough to delete the file and then recreate it with the same filename　with build-in file module? 
Please tell me about use cases.

**Comment by coolrazor007** [comment]
I meant removing select keys from an existing YAML.  Docker-compose.yml for example.

**Comment by git-ogawa** [comment]
> I meant removing select keys from an existing YAML. Docker-compose.yml for example.

I got it.

**Comment by coolrazor007** [comment]
> > I meant removing select keys from an existing YAML. Docker-compose.yml for example.
> 
> 
> 
> I got it.

The reason is that (unless I'm mistaken), you Ansible task only does one key at a time.  It would be cumbersome to recreate a larger YAML file this way.  

I guess two feature requests:
1: delete specific keys
2: take in a list of keys on a single task (although, at this point I'd be asking myself why I don't just use the copy module with a YAML file)

**Comment by git-ogawa** [comment]
You can update multiple values in the `update` field as follows. So it is not hard to add a new option such as "removed" in order to remove existing keys.

```yml
- name: Remove the existing keys
  git_ogawa.yaml.update_yaml:
    path: /path/to/file
    update:
      - key: key1
        removed: true
      - key: key2
        removed: true
      - # continue
```

This will meet the first of your requests.
The second of the requests is a little more difficult to implement immediately but I think it would be sufficient to loop the task with keys to be removed. 

```yml
vars:
  removed_keys:
    - key1
    - key2
    - key3
    # continue

- name: Remove the existing keys
  git_ogawa.yaml.update_yaml:
    path: /path/to/file
    update:
      - key: "{{ item }}"
        removed: true
    loop: "{{ removed_keys }}
```
